version: "3.8"

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ros2_gz_dev

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../ros2_ws:/ros2_ws

    network_mode: host
    tty: true
    stdin_open: true

    # Enable NVIDIA runtime for GPU support
    runtime: nvidia
